name: BilyabitsRDP (Version 2.0.2)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # auto restart every 6 hours

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure RDP and Firewall
        shell: pwsh
        run: |
          Write-Host "Enabling RDP and configuring firewall..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "RDP Enabled successfully."

      - name: Create default user
        shell: pwsh
        run: |
          Write-Host "Creating default user: bilyabits"
          net user bilyabits Cj123 /add
          net localgroup administrators bilyabits /add
          Write-Host "User bilyabits added to administrators."

      - name: Install Tailscale
        shell: pwsh
        run: |
          Write-Host "Installing Tailscale..."
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath ".\tailscale-setup.exe" -ArgumentList "/quiet" -Wait
          Write-Host "Tailscale installed successfully."

      - name: Restore Tailscale state if available
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Write-Host "Restoring previous Tailscale state if exists..."
          if (Test-Path "C:\ProgramData\Tailscale") { Remove-Item "C:\ProgramData\Tailscale" -Recurse -Force }
          try {
            gh run download --dir "C:\ProgramData\Tailscale"
            Write-Host "Tailscale state restored successfully."
          } catch {
            Write-Host "No previous Tailscale state found or unable to download."
          }

      - name: Start Tailscale
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          Write-Host "Starting Tailscale..."
          Start-Service Tailscale
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $env:TAILSCALE_AUTH_KEY --hostname bilyabits-runner --accept-routes --accept-dns=true
          $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
          Write-Host "Tailscale started successfully. IP: $ip"

          $log = @"
          ===== RDP SESSION LOG =====
          Version: 2.0.2
          Username: bilyabits
          Password: Cj123
          IP Address: $ip
          Timestamp: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
          ============================
          "@
          $log | Out-File -FilePath "rdp-credentials.txt"
          Write-Host $log

      - name: Compress and save Tailscale state
        shell: pwsh
        run: |
          Write-Host "Saving Tailscale state..."
          Stop-Service Tailscale
          Compress-Archive -Path "C:\ProgramData\Tailscale" -DestinationPath "tailscale-state.zip" -Force
          Start-Service Tailscale
          Write-Host "Tailscale state saved and service restarted."

      - name: Upload Tailscale state
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-state
          path: tailscale-state.zip

      - name: Upload RDP credentials
        uses: actions/upload-artifact@v4
        with:
          name: rdp-credentials
          path: rdp-credentials.txt
