name: BilyabitsRDP (Version 1.9.8)

on:
  schedule:
    - cron: "0 */6 * * *" # Auto restart every 6 hours
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    env:
      GH_TOKEN: ${{ secrets.RESTART_TOKEN }}
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}

    steps:
      - name: Configure Core RDP Settings
        run: |
          Write-Host "Enabling RDP and configuring policies..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Install Tailscale
        run: |
          Write-Host "Installing Tailscale..."
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath ".\tailscale-setup.exe" -ArgumentList "/quiet" -Wait
          Write-Host "Tailscale installed successfully."

      - name: Restore Tailscale State (if available)
        continue-on-error: true
        run: |
          Write-Host "Attempting to restore previous Tailscale state..."
          Write-Host "Checking for existing tailscale-state artifact..."
          gh run download --name tailscale-state --dir "C:\ProgramData\Tailscale" || Write-Host "No previous state found, skipping restore."

      - name: Start Tailscale
        run: |
          Write-Host "Starting Tailscale and authenticating..."
          Start-Service Tailscale
          tailscale up --authkey $env:TAILSCALE_AUTH_KEY --hostname bilyabits-runner --accept-routes --accept-dns=true --ssh=true
          Write-Host "Tailscale started successfully."
          Write-Host "Fetching assigned IP address..."
          $ip = tailscale ip -4
          Write-Host "Tailscale IP Address: $ip"

      - name: Create RDP User (bilyabits)
        run: |
          Write-Host "Creating or updating RDP user account..."
          $username = "bilyabits"
          $password = "Cj123"
          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
            Write-Host "User already exists. Updating password..."
            net user $username $password
          } else {
            Write-Host "User not found. Creating user..."
            net user $username $password /add
            net localgroup administrators $username /add
          }
          Write-Host "User setup complete."

      - name: Log RDP Credentials
        run: |
          Write-Host "===== RDP CREDENTIALS ====="
          Write-Host "Username: bilyabits"
          Write-Host "Password: Cj123"
          $ip = (tailscale ip -4)
          Write-Host "RDP Address: $ip"
          Write-Host "============================"
          Write-Host "Store these credentials temporarily for your remote session."

      - name: Save Tailscale State
        run: |
          Write-Host "Preparing to save Tailscale state..."
          Write-Host "Stopping Tailscale service to release file locks..."
          Stop-Service Tailscale -Force
          Start-Sleep -Seconds 3
          Compress-Archive -Path "C:\ProgramData\Tailscale" -DestinationPath "tailscale-state.zip" -Force
          Write-Host "Uploading Tailscale state..."
          gh upload-artifact tailscale-state.zip --name tailscale-state
          Write-Host "Tailscale state uploaded successfully."
          Write-Host "Restarting Tailscale service..."
          Start-Service Tailscale
          Write-Host "Tailscale service restarted."

      - name: Auto Restart Workflow
        if: always()
        run: |
          Write-Host "Triggering auto restart..."
          gh workflow run "BilyabitsRDP (Version 1.9.8)" --ref main
          Write-Host "Workflow restart triggered successfully."

      - name: Keep Session Alive
        run: |
          Write-Host "RDP session ready. Workflow will auto-restart every 6 hours."
          Start-Sleep -Seconds 21600 # 6 hours
