name: BilyabitsRDP (Version 1.9.5)
on:
  schedule:
    - cron: "0 */6 * * *" # Auto restart every 6 hours
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Configure Core RDP Settings
        run: |
          Write-Host "Enabling RDP and configuring policies..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Install Tailscale
        run: |
          Write-Host "Installing Tailscale..."
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath ".\tailscale-setup.exe" -ArgumentList "/quiet" -Wait
          Write-Host "Tailscale installed successfully."

      - name: Restore Tailscale State (if available)
        continue-on-error: true
        run: |
          Write-Host "Attempting to restore previous Tailscale state..."
          $artifactUrl = "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts"
          Write-Host "Checking for existing tailscale-state artifact..."
          gh run download --name tailscale-state --dir "C:\ProgramData\Tailscale" || Write-Host "No previous state found, skipping restore."

      - name: Start Tailscale
        run: |
          Write-Host "Starting Tailscale and authenticating..."
          Start-Service Tailscale
          Start-Service Tailscale-IPN
          tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --hostname github-runner
          Write-Host "Tailscale started successfully."
          Write-Host "Fetching assigned IP address..."
          $ip = tailscale ip -4
          Write-Host "Tailscale IP Address: $ip"

      - name: Create RDP User
        run: |
          Write-Host "Creating RDP user account..."
          $username = "runneradmin"
          $password = [System.Web.Security.Membership]::GeneratePassword(16, 2)
          net user $username $password /add
          net localgroup administrators $username /add
          Write-Host "User created successfully."

      - name: Log RDP Credentials
        run: |
          Write-Host "===== RDP CREDENTIALS ====="
          Write-Host "Username: runneradmin"
          Write-Host "Password: $password"
          Write-Host "RDP Address: $ip"
          Write-Host "============================"
          Write-Host "Store these credentials temporarily for your remote session."

      - name: Save Tailscale State
        run: |
          Write-Host "Preparing to save Tailscale state..."
          Write-Host "Stopping Tailscale service to release file locks..."
          Stop-Service Tailscale -Force
          Stop-Service Tailscale-IPN -Force
          Start-Sleep -Seconds 3
          Compress-Archive -Path "C:\ProgramData\Tailscale" -DestinationPath "tailscale-state.zip" -Force
          Write-Host "Uploading Tailscale state..."
          gh upload-artifact tailscale-state.zip --name tailscale-state
          Write-Host "Tailscale state uploaded successfully."
          Write-Host "Restarting Tailscale service..."
          Start-Service Tailscale
          Start-Service Tailscale-IPN
          Write-Host "Tailscale service restarted."

      - name: Keep Session Alive
        run: |
          Write-Host "RDP session ready. Workflow will auto-restart every 6 hours."
          Start-Sleep -Seconds 21600 # 6 hours
